const waEvents = require('./test-wa-events-with-sessions.json');
const eventConvert = require('../WildApricotConversions');

describe('converts an array of events(1 item which is recurring session)', () => {
    test('it should convert recurring event', () => {
        let events = eventConvert(waEvents);
        console.log(events);
        expect(events).toEqual([
            {
                Id: 2267437,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-02-24T10:00:00-05:00',
                EndDate: '2018-02-24T17:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 1 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2268653,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-02-26T10:00:00-05:00',
                EndDate: '2018-02-26T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 2 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2268654,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-02-27T10:00:00-05:00',
                EndDate: '2018-02-27T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 3 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2268655,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-02-28T10:00:00-05:00',
                EndDate: '2018-02-28T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 4 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2268656,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-03-01T10:00:00-05:00',
                EndDate: '2018-03-01T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 5 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2268657,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-03-02T10:00:00-05:00',
                EndDate: '2018-03-02T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 6 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2268658,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-03-03T10:00:00-05:00',
                EndDate: '2018-03-03T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 7 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2293459,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-03-05T10:00:00-05:00',
                EndDate: '2018-03-05T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 8 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2293460,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-03-06T10:00:00-05:00',
                EndDate: '2018-03-06T20:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 9 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            },
            {
                Id: 2293461,
                Url: 'https://api.wildapricot.org/v2/accounts/57611/Events/2832286',
                EventType: 'Regular',
                StartDate: '2018-03-07T10:00:00-05:00',
                EndDate: '2018-03-07T17:00:00-05:00',
                Location: 'Fraser Bicycle, 3162 Packard St, Ann Arbor, MI 48108',
                RegistrationEnabled: false,
                RegistrationsLimit: null,
                PendingRegistrationsCount: 0,
                ConfirmedRegistrationsCount: 0,
                CheckedInAttendeesNumber: 0,
                InviteeStat: { NotResponded: 0, NotAttended: 0, Attended: 0, MaybeAttended: 0 },
                Tags: [ 'education', 'meeting', 'social', 'workouts' ],
                AccessLevel: 'Public',
                StartTimeSpecified: true,
                EndTimeSpecified: true,
                HasEnabledRegistrationTypes: false,
                Name: 'Fit Kit Sizing - Try on the New Kit!!!!',
                parentId: 2832286,
                Title: 'Fit Kit Sizing - Try on the New Kit!!!! (session 10 of 10)',
                isRecurringSession: true,
                isOrganizedEvent: undefined
            }
        ]);
    });
})

